### ISSUE TITLE
[Day1]Win→VMでpingを送るとホストに到達できない(多数報告有)

### ISSUE THREAD

**Issue by Hamaguri-0414** [ohkilab/SU-CSexpA#38]
試して上手く行った解決策

・再起動を繰り返して4回目で成功

・コマンドプロンプトを4つ開いてping攻撃を繰り返す

今のところWIndows11でのみ確認されている

**Comment by Ayoshida0316** [comment]
試して上手くいった例

- 再起動およびMACアドレスの変更

**Comment by Hamaguri-0414** [comment]
ありがとうございます！closeします
