### ISSUE TITLE
モニターなしでの接続方法についての画像がややこしい

### ISSUE THREAD

**Issue by toi11820** [ohkilab/SU-CSexpA#77]
「モニタがない状況でのRaspberryPiの接続（任意）」ページの「PCの有線LANデバイスにIPアドレスを設定」でイーサネットのプロパティを開く部分の画像がややこしいです．画像では，イーサネット１とイーサネット２があって，イーサネット２を選択しているようになっていますが，そちらはVirtual Boxの方なので，正しくはイーサネット１を選択しないといけないです．

**Comment by joko0811** [comment]
対応済み
- https://github.com/ohkilab/SU-CSexpA/commit/974a60f066ed83cff967b2235e9f87da5df76005
